# version: "3.9"

# services:
#   api:
#     build: .
#     container_name: rag-job-api
#     env_file: .env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:5
#     container_name: rag-job-mongo
#     restart: always
#     environment:
#       MONGO_INITDB_DATABASE: ragdb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
