# version: "3.9"

# services:
#   app:
#     build: .
#     container_name: aiproj
#     volumes:
#       - .:/app
#       - chroma_data:/chroma/data # persistent vector DB
#     working_dir: /app
#     command: python main.py
#     environment:
#       - HOME=/root
#       - PYTHONUNBUFFERED=1

# volumes:
#   chroma_data:
